export const URL_CREATE_REQUEST = 'URL_CREATE_REQUEST';
export const URL_CREATE_SUCCESS = 'URL_CREATE_SUCCESS';
export const URL_CREATE_FAIL = 'URL_CREATE_FAIL';


export const URL_REDIRECT_REQUEST = 'URL_REDIRECT_REQUEST';
export const URL_REDIRECT_SUCCESS = 'URL_REDIRECT_SUCCESS';
export const URL_REDIRECT_FAIL = 'URL_REDIRECT_FAIL';
